tweets = [
  "GO PRACTICE!",
  "Hey Brett and Eddy, did you practice today?",
  "This is Ling Ling mother, Ling Ling already practice 40 hours today, how about you?",
  "Ling Ling practiced 40 hours today and has a doctorate, why are you still in Twitter??",
  "I SAID GO PRACTICE!!!",
  "Brett and Eddy are judging you right now because you are not practicing.",
  "PAUSE. STOP READING THIS TWEET. GO PRACTICE.",
  "Someone is not practicing today...",
  "How many hours did you practice today? 0? Okay... *judges you*",
  "WHY ARE YOU NOT PRACTICING 😩😩😩",
  "How about you start PRACTICING NOW",
  "Can you hear that? It's Ling Ling's evil laugh because you're still not practicing.",
  "40. HOURS. A. DAY. NO. EXCUSES.",
  "Go practice!",
  "STOP SCROLLING AND GO PRACTICE",
  "This is a daily reminder that YOU NEED TO PRACTICE",
  "GO PRACTICE! @TwoSetViolin is watching you 👀",
  "How's your piece going? OH RIGHT, YOU DID NOT PRACTICE.",
  "HOW MANY TIMES DO I HAVE TO SAY YOU NEED TO PRACTICE",
  "Hilary Hahn called, she said 'Go practice!'",
  "Sorry, Ling Ling can't come to the phone right now because she's busy practicing.",
  "Brett and Eddy did not perform the Tchaikovsky violin concerto for you not to practice",
  "RT IF YOU PRACTICED TODAY",
  "Hey @TwoSetViolin, did you practice today?",
  "GET OFF YOUR PHONE AND START PRACTICING!!",
  "Sibelius is crying right now because you are not practicing",
  "Tchaikovsky is crying right now because you are not practicing",
  "Mozart is crying right now because you are not practicing",
  "Paganini is crying right now because you are not practicing",
  "Beethoven is crying right now because you are not practicing",
  "Did you practice 40 hours today?",
  "SHAME. SHAME. SHAME.",
  "The number of hours you need to practice today is the number of violin charades @TwoSetViolin made. GO PRACTICE!",
  "Mateeeyy, you should go practiceeee.",
  "If you can use Twitter today, you can practice 40 hours today!",
  "There is only one thing you need to do today, and that is to PRACTICE.",
  "If you're looking for a sign, this is it. GO PRACTICE.",
  "You do viola jokes in a daily but you can't even practice 😭😭",
  "PRACTICE. That's it. That's the tweet.",
  "Right now you're just begging to be dissed by @TwoSetViolin in their next diss track because you did not practice",
  "Hey you, why you not practicing huh? (oof)",
  "As Brett said, 'You got skills but your caprices' dry like a panini (eugh)'",
  "Please make my life easier and go practice!!",
  "You shouldn't need this many reminders for you to go practice",
  "PRACTICE PRACTICE PRACTICE PRACTICE",
  "Is your instrument in quarantine? BECAUSE YOU BOTH ARE SOCIAL DISTANCING.",
  "PLAY THE GODDAMN INSTRUMENT, KAREN",
  "Go Practice. GO PRACTICE. G O P R A C T I C E. go practice.",
  "You know what's the word for the day? It's PRACTICE!",
  "YOU'RE ON YOUR PHONE AGAIN? LING LING ALREADY PRACTICED 40 HOURS TODAY",
  "Did you even touch your instrument today??",
  "Maybe if you practiced you won’t be struggling",
  "You know why you’re struggling? Because you’re not practicing.",
  "Why wait for tomorrow when you can practice today?",
  "You have @TwoSetViolin merch but you’re not practicing 😩",
  "P-r-a-c-t-i-c-e. Practice.",
  "Practice or @TwoSetViolin won’t notice you",
  "So many excuses. GO PRACTICE!",
  "#PracticeHour every hour of every day",
  "You know what’s free? Practice."
]